### ISSUE TITLE
Android Not working on RN 0.33

### ISSUE THREAD

**Issue by avishayil** [react-native-component/react-native-smart-splash-screen#6]
1. Cannot find the function `getReactNativeHost` on `MainActivity.java`
2. On `@Override
    protected ReactRootView createRootView()`:
    `MainActivity.java:49: error: method does not override or implement a method from a supertype
    @Override
    ^`
3. `MainActivity.java:81: error: cannot find symbol
        return super.createRootView();
                    ^
  symbol: method createRootView()`

**Comment by cyqresig** [comment]
The installation of readme is updated for supporting react-native 0.33 (android).
